### ISSUE TITLE
README talks about pow-js instead of pow-nodejs

### ISSUE THREAD

**Issue by thisredone** [iotaeco/iota-pico-pow-nodejs#2]
This:
> The library contains the Curl proof of work algorithm in plain NodeJS.

is confusing. It should be said that it provides interface to `libccurl.dll` and therefore is very fast.

Installation should also be updated from this:
```npm install @iota-pico/pow-js --save```
to this:
```npm install @iota-pico/pow-nodejs --save```

**Comment by obany** [comment]
Updated for next release, it now says:

**The library contains the Curl proof of work algorithm for use with NodeJS.**

**It is a wrapper around the ccurl binaries [https://github.com/iotaledger/ccurl](https://github.com/iotaledger/ccurl) and is very fast.**

Install command also fixed.
