### ISSUE TITLE
Transpile to es2015

### ISSUE THREAD

**Issue by thisredone** [iotaeco/iota-pico-pow-nodejs#3]
It would be useful to to run this on environments that haven't yet been updated to node >= 8 and so don't have async/await.
Maybe at least import something like `@iota-pico/pow-nodejs/es5` could be used if you guys don't want the whole package transpiled.

**Comment by obany** [comment]
Unfortunately I don't have the time to maintain and test with lots of older versions of node. Version 8 will be the minimum supported.

It's not really the code itself that is the problem but libraries like ffi which is used to interface with the binaries, this would also have to be tested across windows/linux/mac as well.

If you want to use with a version of node that does not support async/await and can't do the transpilation as part of your own build you can always use the https://github.com/iotaeco/iota-pico-lib-nodejs all-in-one library. This library already uses regeneratorRuntime in place of async/await.

**Comment by thisredone** [comment]
Oky
